version: "3"

services:
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.j
    depends_on:
      - "redis"
      - "db"
    networks:
      - back-tier
  redis:
    image: redis
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier
  db:
    image: postgres:9.4
    container_name: db
    environment:
      POSTGRES_DATABASE: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - back-tier
networks:
  back-tier: